### ISSUE TITLE
Ports column in service view is showing target port name, instead of int value

### ISSUE THREAD

**Issue by rati3l** [perber/kdd#128]
![image](https://user-images.githubusercontent.com/34656130/223341377-fdbf407b-47ef-4f70-b650-7ec02d450525.png)

**Comment by rati3l** [comment]
Looks like the service object is not storing the data about port number, if using named ports:
```
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: http
```
